export const postContentConstants = {
  REQUEST_POST_CONTENT      : 'REQUEST_POST_CONTENT',
  RECEIVE_POST_CONTENT      : 'RECEIVE_POST_CONTENT',
  FETCH_POST_CONTENT_ERROR  : 'FETCH_POST_CONTENT_ERROR',
  RESET_ERROR               : 'RESET_ERROR',
}