export const postsConstants = {
  SELECT_SUBREDDIT      : 'SELECT_SUBREDDIT',
  INVALIDATE_SUBREDDIT  : 'INVALIDATE_SUBREDDIT',
  REQUEST_POSTS         : 'REQUEST_POSTS',
  RECEIVE_POSTS         : 'RECEIVE_POSTS',
  FETCH_POSTS_ERROR     : 'FETCH_POSTS_ERROR',
  RESET_ERROR           : 'RESET_ERROR',

}